name: 'Test github action'

on:
    push:
        branches: ["feature-env-folder"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]

        steps:
        - uses: actions/checkout@v4

        - name: Set up python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
           python -m pip install --upgrade pip
           pip install requirements_dev.txt
           pip install requirements.txt

        - name: Pytest Tests
          run: |
            pytest -v